apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: educacionit-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Marce-Sica/DevOps_Engineer/desafio_14
    targetRevision: HEAD
    path: desafio_12/helm/educacionit-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
